@startuml
!theme cyborg
hide circle
'avoid problems with angled crows feet
skinparam linetype ortho

entity "S_Messung" as s01 #line:yellow;back:yellow {
*messung_id : integer <<generated>>
--
loaddate : timestamp
recordsource : varchar(10)
}
entity "R_Land" as rland #line:gray;back:gray {
*land_id : integer <<pk>>
--
ort: varchar(200) 
erstell_am: timestamp
quelle: varchar(20)
}

entity "L_fahrzeuglink" as lfahrzeuglink #line:red;back:red {
*lf_id : binary <<generated>>
--
v_id : binary <<fk>>
loaddate : timestamp
recordsource : varchar(10)
}

entity "S_kfzzuordnung" as skfzzuordnung #line:yellow;back:yellow {
*lf_id: binary <<fk>>
*loaddate : timestamp
--
kfz_kennzeichen: varchar(20)
loaddate : timestamp
recordsource : varchar(10)
}

entity "L_kundenlink" as lkundenlink #line:red;back:red {
*lk_id : binary <<generated>>
--
k_id: binary <<fk>>
loaddate : timestamp
recordsource : varchar(10)
}

entity "R_ort" as rort #line:gray;back:gray {
*r_ort_id : integer <<pk>>
--
ort: varchar(200)
land_id: integer <<fk>>
erstell_am: timestamp
quelle: varchar(20)
}

entity "H_fahrzeug" as hfahrzeug #line:blue;back:blue {
*v_id : integer <<generated>>
--
fin: varchar(17) <<unique>>
loaddate : timestamp
recordsource : varchar(10)
}
entity "S_fahrzeugdaten" as sfahrzeugdaten #line:yellow;back:yellow {
*lf_id : binary <<fk>> 
*loaddate : timestamp
--
baujahr: integer
modell: varchar(200)
erstell_am: timestamp
quelle: varchar(20)
}
entity "H_kunde" as hkunde #line:blue;back:blue {
*k_id : integer <<generated>>
--
loaddate : timestamp
recordsource : varchar(10)
}
entity "s_kundendaten" as skundendaten #line:yellow;back:yellow {
*lk_id : binary <<fk>>
*loaddate : timestamp
--
ort_id: integer <<fk>>
vorname: varchar(200)
nachname: varchar(200)
anrede: varchar(20)
geschlecht: varchar(20)
geburtsdatum: date
erstell_am: timestamp
quelle: varchar(20)
}
entity "s_hersteller" as shersteller #line:yellow;back:yellow {
*lf_id : binary <<fk>>
*loaddate : timestamp
--
hersteller: varchar(200)
erstellt_am: timestamp
quelle: varchar(20)
}

rort --|> rland
skundendaten --{ rort
shersteller --{ lfahrzeuglink
lkundenlink }-- hkunde
skundendaten --{ lfahrzeuglink
skundendaten --{ lkundenlink
sfahrzeugdaten --{ lfahrzeuglink
skfzzuordnung --{ lfahrzeuglink
lfahrzeuglink }-- hfahrzeug
@enduml
